### PR TITLE
Docs 1.5 Update

### PR DESCRIPTION
**Pull request by MFA-X-AI**
# Description

This PR updates the current docs to the 1.5 update. 

## References

https://github.com/XpressAI/xircuits/releases/tag/v1.5.0
https://github.com/XpressAI/xircuits/releases/tag/v1.5.1

https://github.com/XpressAI/xircuits.io/issues/12

## Pull Request Type

- [x] Frontend (HTML / CSS / TS)
- [x] Xircuits Documentation (Tutorials, Guides, References)
- [x] Examples (Component libraries, project templates)
- [ ] Others (Please Specify)

## Type of Change

- [x] Frontend (HTML / CSS / TS)
- [x] New documentation (Entirely new documentation files)
- [x] Updates to current documentation
- [x] Minor grammar fixes

# Notes

For now, will need proofreading help on existing documents. Feel free to add suggestions on what's missing though, will add  them in the next PR. 😄

### CODE REVIEW

**Comment by yuenherny** [comment]
A few comments @MFA-X-AI :

1. Add a WARNING or IMPORTANT box to remind users to make a virtual environment before `pip install xircuits` at the [installation page](http://localhost:3000/docs/getting-started/Installation).
2. I remembered I have difficulty to delete the connector line between components last time (I had to delete one of the components to get rid of the wrong connector). Perhaps a quick note somewhere between **Right Click Context Menu** and **Component Related Interface**  to teach users how to do this. 
3. In **Prerequisites** item 2, I suggest the following amendments:
> Ensure that you have the `examples` folder in your working directory. After Xircuits is installed, you can download it by running the `xircuits-examples` in the command line.
4. Overall, there are instances where the first letter of a name isn't capitalized. E.g. "Python" spelled as "python", "Xircuits" as "xircuits", "Resnet50" as "resnet50", "Mobilenet" as "mobilenet", and so on.
5. There are also instances where the code-format isn't enforced on code-related names. E.g. at Examples > Computer Vision > Keras > Training an Image Classifier Image from Scratch, "LiteralString" (with code formatting) is spelled as "literal string" - which might confuse Python beginners. Similar goes to `Create2DInputModel` later in the passage and file extension like `.xircuits` and `.pth` in other pages.
image
6. At Examples > Computer Vision > PyTorch > Training a Torch ML Model, there's a misspelling of "fashion".
image
There's another misspelling of "fashionMNIST" later in the page:
image

I'll continue with Pycaret, Spark, Developer Guide, Technical Concepts, References and FAQ tomorrow.

**Comment by yuenherny** [comment]
## Pycaret AutoML
### NLP
Looks good. No further comments.

### Spark
#### Spark Installation
1. Do you mean "Xircuits Spark components" here?
image
2. I noticed there are a lot of instances of "pip install" or "pip installed". Is this intended as a recommendation of using `pip` over other installation methods?
3. Perhaps a link would be great
image

#### Xircuits Spark Submit
1. Do you mean "If not you can perform"?
image
2. Missing forward slash symbol here:
image

### Developer Guide
#### Literal & Hyperparameter Components
1. In Hyperparameter Components, perhaps can include what would the command be if users were to run thing not with hyperparameter components, to show that using hyperparameter components is way more convenient:
image

No further comments for Technical Concepts, References and FAQs.

**Review by yuenherny — APPROVED** [review]
Great work! 

However there are some minor things to fix. Kindly refer to the comments [here](https://github.com/XpressAI/xircuits.io/pull/11#issuecomment-1219748555) and [here](https://github.com/XpressAI/xircuits.io/pull/11#issuecomment-1220235957) for more info.

Once you rectified the comments, this PR is good to be merged.

Side note, referring to this item:
> Overall, there are instances where the first letter of a name isn't capitalized. E.g. "Python" spelled as "python", "Xircuits" as "xircuits", "Resnet50" as "resnet50", "Mobilenet" as "mobilenet", and so on. (This can be done much later when you're not that occupied)

I am more than happy to help with this if you need extra pair of hands. It's kinda tedious to do but it does increase the aesthetics a bit (maybe because I'm a person with slight OCD.

**Comment by MFA-X-AI** [comment]
Thanks as always for the in-depth PR @yuenherny, I've also included your suggestions and addressed the venv tooltip.

**Pull request merged**
