### PR TITLE
Image / gif migration as static assets

### PR DESCRIPTION
**Pull request by MFA-X-AI**
In the current docs, certain images / gifs, especially those enclosed in html tags are actually pulled from `githubusercontent`. 
As per suggested by the [official docs](https://docusaurus.io/docs/static-assets), resources should be hosted as statics assets which is created when building the web.

This PR migrates all the images / gifs from the docs to the static folder, while fixing the links to proper resource paths.
For house keeping purposes, I've kept the structure of the documentation image resources to follow the doc structure, ie `xircuits-interface.png` which is used in `/docs/user-guide/xircuits-interface.md` is hosted at `/static/img/docs/user-guide/xircuits-interface.png`.

**To Check:**
Ensure that all images / gifs are visible.

### CODE REVIEW

**Review by annabelle1217 — COMMENTED** [review]
Able to build and no missing images found

Found the main page "Get Started" button go to 404, but the Home will be replaced with another template right?
image

**Comment by MFA-X-AI** [comment]
Oh, that is interesting. https://github.com/XpressAI/xircuits.io/pull/9/commits/38f01c1b4af17f2482f08390f5d447240e85d785 should've fixed that one. Where does it link to in your build?

**Comment by annabelle1217** [comment]
It goes to http://localhost:3000/docs/index
image

**Comment by annabelle1217** [comment]
Oh my bad, I must be running master

**Comment by annabelle1217** [comment]
Ya, it fixed in current branch. Lemme quick check the images

**Review by annabelle1217 — APPROVED** [review]
Done checking. All good.

**Comment by MFA-X-AI** [comment]
Awesome. Thanks for the review. Merging~

**Pull request merged**
